### ISSUE TITLE
Missing one check

### ISSUE THREAD

**Issue by ziobron** [mBialczak/university-db#3]
What about checking ` ASSERT_NE(valid_rec_`.index(), non_existing_index); `

https://github.com/mBialczak/university-db/blob/d1877fc27b745d01e681501ec5700b245bad317e/tests/UniversityDBTests/UniversityDB-MT.cpp#L203-L205

**Comment by mBialczak** [comment]
Added the missing check with commit on the branch universityDB-OOP-basic
