### ISSUE TITLE
Testing random number generators

### ISSUE THREAD

**Issue by ziobron** [mBialczak/university-db#4]
For testing such stuff we can have two approaches. First (usually easiest) is to use the same seed for random number generators. It will cause that RNG returns the same data. This is possible for stl generators.
The other option is to use some mocks instead of random numbers generators.

https://github.com/mBialczak/university-db/blob/abf928cac44e3a996dccd44c028458bfbb433ee4/tests/DBdataGeneratorTests/DBdataGenerator-UT.cpp#L155-L159

**Comment by mBialczak** [comment]
Added correction with commit on the branch universityDB-OOP-advanced.

The correction included adding hard-coded seed while testing.
